/* prettier-ignore-start */

/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
// Import Routes
import { Route as ToolImport } from './routes/$tool';
import { Route as rootRoute } from './routes/__root';
import { Route as DoctorImport } from './routes/doctor';
import { Route as IndexImport } from './routes/index';
import { Route as PlaygroundImport } from './routes/playground';
import { Route as PluginsImport } from './routes/plugins';

// Create/Update Routes

const PluginsRoute = PluginsImport.update({
  path: '/plugins',
  getParentRoute: () => rootRoute,
} as any);

const PlaygroundRoute = PlaygroundImport.update({
  path: '/playground',
  getParentRoute: () => rootRoute,
} as any);

const DoctorRoute = DoctorImport.update({
  path: '/doctor',
  getParentRoute: () => rootRoute,
} as any);

const ToolRoute = ToolImport.update({
  path: '/$tool',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/$tool': {
      id: '/$tool';
      path: '/$tool';
      fullPath: '/$tool';
      preLoaderRoute: typeof ToolImport;
      parentRoute: typeof rootRoute;
    };
    '/doctor': {
      id: '/doctor';
      path: '/doctor';
      fullPath: '/doctor';
      preLoaderRoute: typeof DoctorImport;
      parentRoute: typeof rootRoute;
    };
    '/playground': {
      id: '/playground';
      path: '/playground';
      fullPath: '/playground';
      preLoaderRoute: typeof PlaygroundImport;
      parentRoute: typeof rootRoute;
    };
    '/plugins': {
      id: '/plugins';
      path: '/plugins';
      fullPath: '/plugins';
      preLoaderRoute: typeof PluginsImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ToolRoute,
  DoctorRoute,
  PlaygroundRoute,
  PluginsRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$tool",
        "/doctor",
        "/playground",
        "/plugins"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$tool": {
      "filePath": "$tool.tsx"
    },
    "/doctor": {
      "filePath": "doctor.tsx"
    },
    "/playground": {
      "filePath": "playground.tsx"
    },
    "/plugins": {
      "filePath": "plugins.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
